#!/bin/bash
echo "Testing diagnostics with 10-second interval for quick verification..."
echo ""
echo "To test, modify src/diagnostics.rs line 36 to use 10 seconds instead of 30 minutes:"
echo "  let mut interval = interval(Duration::from_secs(10)); // Changed from interval_minutes * 60"
echo ""
echo "Then run: cargo run --example 07_with_diagnostics --features axum"
echo ""
echo "You should see health check logs every 10 seconds like:"
echo "[INFO] === Relay Health Check ==="
echo "[INFO] Connections: 0 (△ +0)"
echo "[INFO] Subscriptions: 0 total, 0.00 avg/conn (△ +0)"
echo "[INFO] Scopes: 0 active"
echo "[INFO] Indexes:"
echo "[INFO]   - Authors: 0 entries (△ +0)"
echo "[INFO]   - Kinds: 0 entries (△ +0)"
echo "[INFO]   - Tags: 0 entries (△ +0)"